## 關鍵詞提取

TF 詞頻 (Term Frequency): 
是指某一個文字在某一個文件中所出現的頻率。

可用式子表示為 tf(t,d): t詞在d文件中出現的頻率。

例如：十萬 / 青年 / 十萬 / 肝， 十萬出現了2次，總共有3個字詞，

因此tf(t,d) = 2/3 = 0.66666。

IDF 逆向文件頻率 (Inverse Document Frequent):定義為文件數除以某特定文字有被多少文件所提及的數量取log

可用式字表示為 idf(t,D) = log (D/dt)

(D為文件總數，dt為提及t文字的文件數量)

例如：總共有10個文件，其中有5個文件提及“十萬“，則IDF為 log(10/5) = 0.3。


In [20]:
corpus2 = ["The sky is blue",
          "The sky is not blue"
         ]

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
# step 1
vectoerizer = CountVectorizer(min_df=1, max_df=1.0, token_pattern='\\b\\w+\\b')
# step 2
vectoerizer.fit(corpus2)
# step 3
bag_of_words = vectoerizer.get_feature_names()
print("Bag of words:")
print(bag_of_words)
print(len(bag_of_words))
# step 4
X = vectoerizer.transform(corpus2)
print("Vectorized corpus:")
print(X.toarray())
# step 5
print("index of `的` is : {}".format(vectoerizer.vocabulary_.get('not')))

Bag of words:
['blue', 'is', 'not', 'sky', 'the']
5
Vectorized corpus:
[[1 1 0 1 1]
 [1 1 1 1 1]]
index of `的` is : 2


In [25]:
from sklearn.feature_extraction.text import TfidfTransformer
# step 1
tfidf_transformer = TfidfTransformer()
# step 2
tfidf_transformer.fit(X.toarray())
# step 3
for idx, word in enumerate(vectoerizer.get_feature_names()):
  print("{}\t{}".format(word, tfidf_transformer.idf_[idx]))
# step 4
tfidf = tfidf_transformer.transform(X)
print(tfidf.toarray())

blue	1.0
is	1.0
not	1.4054651081081644
sky	1.0
the	1.0
[[0.5        0.5        0.         0.5        0.5       ]
 [0.4090901  0.4090901  0.57496187 0.4090901  0.4090901 ]]


/anaconda3/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1089: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):


有人可以用公式來算出上面這一個矩陣嗎？

### 較長的範例

In [14]:
corpus = ["幫我 查下 明天 北京 天氣 怎麼樣",
          "幫我 查下 今天 北京 天氣 好不好",
          "幫我 查詢 去 北京 的 火車",
          "幫我 查看 到 上海 的 火車",
          "幫我 查看 特朗普 的 新聞",
          "幫我 看看 有沒有 北京 的 新聞",
          "幫我 搜索 上海 有 什麼 好玩的",
          "幫我 找找 上海 東方明珠 在哪"
         ]

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
# step 1
vectoerizer = CountVectorizer(min_df=1, max_df=1.0, token_pattern='\\b\\w+\\b')
# step 2
vectoerizer.fit(corpus)
# step 3
bag_of_words = vectoerizer.get_feature_names()
print("Bag of words:")
print(bag_of_words)
print(len(bag_of_words))
# step 4
X = vectoerizer.transform(corpus)
print("Vectorized corpus:")
print(X.toarray())
# step 5
print("index of `的` is : {}".format(vectoerizer.vocabulary_.get('的')))

/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


Bag of words:
['上海', '什麼', '今天', '到', '北京', '去', '在哪', '天氣', '好不好', '好玩的', '幫我', '怎麼樣', '找找', '搜索', '新聞', '明天', '有', '有沒有', '東方明珠', '查下', '查看', '查詢', '火車', '特朗普', '的', '看看']
26
Vectorized corpus:
[[0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0]
 [1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 1 0]
 [0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 1 1]
 [1 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0]]
index of `的` is : 24


In [16]:
from sklearn.feature_extraction.text import TfidfTransformer
# step 1
tfidf_transformer = TfidfTransformer()
# step 2
tfidf_transformer.fit(X.toarray())
# step 3
for idx, word in enumerate(vectoerizer.get_feature_names()):
  print("{}\t{}".format(word, tfidf_transformer.idf_[idx]))
# step 4
tfidf = tfidf_transformer.transform(X)
print(tfidf.toarray())

上海	1.8109302162163288
什麼	2.504077396776274
今天	2.504077396776274
到	2.504077396776274
北京	1.587786664902119
去	2.504077396776274
在哪	2.504077396776274
天氣	2.09861228866811
好不好	2.504077396776274
好玩的	2.504077396776274
幫我	1.0
怎麼樣	2.504077396776274
找找	2.504077396776274
搜索	2.504077396776274
新聞	2.09861228866811
明天	2.504077396776274
有	2.504077396776274
有沒有	2.504077396776274
東方明珠	2.504077396776274
查下	2.09861228866811
查看	2.09861228866811
查詢	2.504077396776274
火車	2.09861228866811
特朗普	2.504077396776274
的	1.587786664902119
看看	2.504077396776274
[[0.         0.         0.         0.         0.3183848  0.
  0.         0.42081614 0.         0.         0.20052115 0.50212047
  0.         0.         0.         0.50212047 0.         0.
  0.         0.42081614 0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.50212047 0.         0.3183848  0.
  0.         0.42081614 0.50212047 0.         0.20052115 0.
  0.         0.         0.         0.         0.         0.
  0.         0.4

/anaconda3/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1089: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
